
public enum Ville {
    //morrocan cities list  
    CASABLANCA, RABAT, FES, MARRAKECH, TANGER, MEKNES, OUJDA, AGADIR, 
    TETOUAN, KENITRA, SAFI, SALE, MOHAMMEDIA, KHOURIBGA, BENI_MELLAL, 
    TAZA, EL_JADIDA, NADOR, SETTAT, BERKANE,  LARACHE, KHEMISSET, 
    GUELMIM, BERRECHID, TIFLET, ESSAOUIRA, OUARZAZATE, TAN_TAN, TAROUDANT, 
    OUEZZANE,  AL_HOCEIMA, BEN_SLIMANE, INEZGANE, 
    TIZNIT, ZAGORA,  TINGHIR
}
